### ISSUE TITLE
Problem with nodeMCU (ESP 8166)

### ISSUE THREAD

**Issue by X-n3t** [SequoiaSan/FlipperZero-Wifi-ESP8266-Deauther-Module#3]
Hello, nice project, congrats. :)

I have been problems with this module.

1º Flash esp8266_deauther.ino.d1_mini.bin in my nodeMCU

2º Copy 2 folders in flipper's SD root:

FlipperZero-Wifi-ESP8266-Deauther-Module/FlipperZeroModule/FlipperZero-ESP8266-Deauth-App/applications/esp8266_deauth/

FlipperZero-Wifi-ESP8266-Deauther-Module/FlipperZeroModule/FlipperZero-ESP8266-Deauth-App/assets/icons/MainMenu/ESP8266Deauth_14/

3º Connect my Flipper Zero Protoboard + nodeMCU to Flipper

4º I run Unleashed firmware and I run program from plugins, [ESP8266]Deauther.

5º I press the reset button (nodeMCU), the program loads but the menu does not respond to the buttons.

Have I forgotten something?

**Comment by X-n3t** [comment]
I have tried to compile:

docker-compose exec dev ./fbt                                         
	ICONS	build/f7-firmware-D/assets/compiled/assets_icons.c
Traceback (most recent call last):
  File "/project/scripts/assets.py", line 274, in <module>
    Main()()
  File "/project/scripts/flipper/app.py", line 34, in __call__
    return_code = self.call()
  File "/project/scripts/flipper/app.py", line 50, in call
    return self.args.func()
  File "/project/scripts/assets.py", line 132, in icons
    temp_width, temp_height, data = self._icon2header(fullfilename)
  File "/project/scripts/assets.py", line 94, in _icon2header
    image = file2image(file)
  File "/project/scripts/flipper/assets/icon.py", line 87, in file2image
    output = __tools.png2xbm(file)
  File "/project/scripts/flipper/assets/icon.py", line 60, in png2xbm
    with Image.open(file) as im:
  File "/project/toolchain/x86_64-linux/python/lib/python3.9/site-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'assets/icons/MainMenu/ESP8266Deauth_14/frame_01.png'
scons: *** [build/f7-firmware-D/assets/compiled/assets_icons.c] Error 1
	CC	applications/cli/cli.c
********** ERRORS **********
Failed building build/f7-firmware-D/assets/compiled/assets_icons.c: Error 1

**Comment by SequoiaSan** [comment]
Hi @X-n3t !
Thanks for trying this project.

I'll try to help you tomorrow with this if you don't mind. I had a hard week :)
We'll try to identify the issue step by step.

**Comment by X-n3t** [comment]
Thanks, I have tried with diferent firmwares, my hardware is a nodeMCU.

**Comment by SequoiaSan** [comment]
@X-n3t 

Greetings again.

Luckily I have found NodeMCU in my 
I  flashed it, connected all the pins and for me everything running OK.

So what I would like to ensure with you first of all:

1. Flash your NodeMCU with [web flasher](https://sequoiasan.github.io/FlipperZero-Wifi-ESP8266-Deauther-Module/)
2. Use latest [Unleashed firmware](https://github.com/Eng1n33r/flipperzero-firmware/releases/tag/cg1-e1ffb4). Deauther located under Plugin -> [ESP8266] Deauther
3. Connection. F (Flipper), E (NodeMCU ESP8266)

F-18 -> F-16
F-14 -> E-TX
F-13 -> E-RX
F-8 -> E-G
F-7 -> E-D5
F-6 -> E-D6
F-5 -> E-D7
F-4 -> E-D8
F-1 -> E-VIN

(Hope I've written all correct above. Too many numbers and characters)

Please, get back to me with the results.

**Comment by X-n3t** [comment]
Ok, thanks :). 
I had only 4 pins(gnd,TX,Rx,3v). What firmware need for nodemcu? I check 4 versions.
![imagen](https://user-images.githubusercontent.com/52056830/184930462-daddcbeb-9be8-4d1c-a15c-bf80e486ed9f.png)


Regards.

**Comment by SequoiaSan** [comment]
I have one of [these](https://www.studiopieters.nl/esp8266-nodemcu-pinout/)
What kind of yours look like?
About firmware - I'm not sure. I flashed it with d1 mini firmware and everything was OK. So try [web flasher](https://sequoiasan.github.io/FlipperZero-Wifi-ESP8266-Deauther-Module/) first. If it will not work we'll proceed with the next steps.

**Comment by X-n3t** [comment]
I flash with nodemcu firmware programmer, web tool doesn't work for me.

I have flashed esp8266_deauther.ino.d1_mini.bin (file is in your GitHub).

The program doesn't load. It's freeze(initializing...).

**Comment by SequoiaSan** [comment]
Can you try this *.bin? I'm not sure that this will help, but I think we can give a try. 
[esp8266_deauther.ino.nodemcu.bin.zip](https://github.com/SequoiaSan/FlipperZero-Wifi-ESP8266-Deauther-Module/files/9353160/esp8266_deauther.ino.nodemcu.bin.zip)

While board is connected can you see the WiFi AP named pwned? Can you enter the web page and use the module? this will ensure that the board itself is working. 
For accessing the Web Interface: 
Connect to the SSID pwned with the password: deauther
Then use a browser to go to http://192.168.4.1/

**Comment by X-n3t** [comment]
This have better face, thanks mate 👍![IMG_20220816_232317.jpg](https://user-images.githubusercontent.com/52056830/184988013-cba76a0f-b94f-4cf8-8636-08c98fee1340.jpg)

**Comment by SequoiaSan** [comment]
Great! Thanks for the investigation :)
I'll add this binary to package soon.

**Comment by X-n3t** [comment]
Thanks good job, my problem was what I used 4 pins 😅, with that mode I could see commands from log opcion( marauder program)... And wifi gui mode works.

**Comment by SequoiaSan** [comment]
So in the end did the new *.bin helped you? :) Just want to know should I include it to package with the reference on this issue.

**Comment by X-n3t** [comment]
Yes, you can share it, it's works!

**Comment by SequoiaSan** [comment]
Great! Thanks again :)

[Added NodeMCU bin to current release](https://github.com/SequoiaSan/FlipperZero-Wifi-ESP8266-Deauther-Module/releases/tag/fzm.v.0.1)

**Comment by TQMatvey** [comment]
Hello, currently trying to use my nodemcu v3 (esp8266) with flipper, i am on unleashed, latest. Flashed the bin file from your releases to my nodemcu, wired up, and it woooorks! after being happy for first 15 seconds, scanned, selected my network, went to attack menu, selected deauth aaaand it does nothin, clicked start, and it shows DEAUTH 0/25, and my phone and other devices are still perfectly connected, any logs i can provide or debugging steps?

**Comment by TQMatvey** [comment]
![NodeMCU-V3](https://user-images.githubusercontent.com/77576395/193182512-f1e1e7ec-1592-4b30-8341-f7d828f8a0d6.png)

**Comment by TQMatvey** [comment]
![AGC_20220930_101336744](https://user-images.githubusercontent.com/77576395/193182845-a946a068-3eb6-49ac-93b3-a28bba72906d.jpg)
![AGC_20220930_101322483](https://user-images.githubusercontent.com/77576395/193182860-0ef6045b-3a9b-4151-8d7b-9c1ac9557a80.jpg)

**Comment by TQMatvey** [comment]
Other attacks like Beacon and Probe work fine
